### ISSUE TITLE
Batch Multi Run File gets too large and confusing to read

### ISSUE THREAD

**Issue by TrajceNikolov** [TravelModellingGroup/XTMF#13]
Although I think the multi-run capability in XTMF is very much an incredibly useful feature, one problem that I have with it is that, when running a lot of runs, the "Batch File" gets too large and very confusing to read in its current format. More importantly, it becomes somewhat difficult to read through the paths when doing a QA before I launch a run. A more readable format would most definitely be welcomed.

**Comment by JamesVaughan** [comment]
My current proposition is to include a new feature into the Multi-run framework to define a template.  This template would contain an attribute for the parameters into the template, and inner XML.  This XML would have its attributes searched for %[ParameterName]% and on invocation of the template have it replaced with the given parameter's value.  This could greatly reduce the amount of duplicate lines, making it easier to validate.

**Comment by JamesVaughan** [comment]
In 8b403b4e75b71599db1438812bdffddcdd742a89 I've implement the logic for templates and the ability to import/execute other multi-run files recursively.  The following files would show how to use a template to create another template that is able to execute a model system.

--TemplateTest.xml--

<Root>
  <import Path="..\..\Input\TemplateTest2.xml" />
  <executeTemplate Name="ExecuteWaitTwice" Dur1="5 seconds" Dur2="10 seconds" />
</Root>

--TemplateTest2.xml--

<Root>
  <template Name="ExecuteWaitTwice" Parameters="Dur1;Dur2">
    <template Name="ExecuteWait" Parameters="Duration">
      <run RunAs="%%Duration%%" Name="%%Duration%%:">
        <ChangeParameter ParameterPath="Wait time" Value="%%Duration%%" />
      </run>
    </template>
    <executeTemplate Name="ExecuteWait" Duration="%Dur1%" />
    <executeTemplate Name="ExecuteWait" Duration="%Dur2%" />
  </template>
</Root>
