### ISSUE TITLE
Module deleted and then not recovered

### ISSUE THREAD

**Issue by TrajceNikolov** [TravelModellingGroup/XTMF#19]
I accidentally deleted my Zone Data module and then "undid" it by pressing control-z. The module was recovered and everything seemed fine, even the parameters themselves. I tried to run the model system, and it failed saying that it couldn't find a parameter from my Zone Data module. I went to look at it, and I couldn't find the problem because all of the parameters were correct. The problem kept on going until I closed XTMF and re-opened it. It is at that point that I saw that the Zone Data Module had "recovered" to all of it's default values - and hence wrong parameters.

**Comment by JamesVaughan** [comment]
I've managed to replicate the issue.  Looking into it now.
