### ISSUE TITLE
XTMF doesn't raise any caution when Toolbox is Missing

### ISSUE THREAD

**Issue by TrajceNikolov** [TravelModellingGroup/XTMF#22]
I just had a problem in which the XTMF could not find the toolbox while it was running, and instead of raising any caution (or error), it kept on running without any suggestion that something was broken aside from the lengthy run time. I only stumbled onto the fact that I hadn't loaded in a toolbox once I tried to go do it manually.

Not sure if this can be fixed, but a small message box would be very helpful.

**Comment by JamesVaughan** [comment]
There was an error where python's sleep method was being called with 500.  Instead of it taking milliseconds it was taking 500 in as the number of seconds to wait.  Failure would only occur after 83 minutes of runtime.  This has been fixed in 1e7f3e0.
