### ISSUE TITLE
Crashing on pasting modules

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/XTMF#24]
When attempting to paste modules (specifically any file output modules - DirectorySeparatedPath, etc.), the program crashes.

**Comment by JamesVaughan** [comment]
I'm currently unable to reproduce this issue but will investigate it further.  If the latest build does not solve your problems getting the offending model system could aid in figuring out why this is happening.

**Comment by JamesVaughan** [comment]
User was no longer able to reproduce the error with the current version.
