### ISSUE TITLE
Fully Hide Meta-Module Hidden Parameters in XTMF

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#31]
Currently  meta-modules hide parameters by changing the text from white to grey. Would be helpful to have the parameters disappear from view fully to make meta-modules more compact.

**Comment by JamesVaughan** [comment]
I believe this makes sense for meta-modules.  I would still prefer regular modules to have them greyed out and sorted to the bottom so you don't lose the ability to see them again.

**Comment by BrendanReilly** [comment]
Changes in the most recent commit completely hide meta-module hidden parameters by default. Visbility can be toggled by an option added in the View menu.
