### ISSUE TITLE
XTMF tabs

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#33]
After enough tabs are opened in XTMF, they start to disappear. Although they are all still listed in the drop down menu on the side, there is no visual indication that a tab has disappeared, resulting in potential confusion about the seemingly lost tab. Would be nice to have some intuitive visual sign that there are additional hidden tabs. 

Also, at some point tabs start opening on the left rather than the right. Would also be good to have consistency on this.

**Comment by JamesVaughan** [comment]
I'm going to leave this issue open until we are either alright with tabs always opening on the left or find a way to get the framework we are using to host the documents to not switch strategies.  Looking at Visual Studio though, they also open new tabs on the left side.

**Comment by JamesVaughan** [comment]
After using XTMF with the new tabs starting on the left I've stopped noticing the change and think it is fine moving forward.
