### ISSUE TITLE
XTMF Project Settings

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#34]
This may be more of a discussion than a request. I have noticed that if you have more than one XTMF, and you open one and change the project settings, they are automatically modified for all other XTMFs. Myabe it is better to have different settings for each XTMF? For example, one may have multiple versions of XTMF on one's computer, in case one has to rerun old projects and wants consistent results. In this scenario, it would be good to keep the projects of each version in separate directories, in order to ensure that the correct project is always run with the correct version, and there are no modifications made to the model system due to lack of backwards compatibility (missing modules, wrong number of parameters, etc). Thoughts?

**Comment by JamesVaughan** [comment]
This functionality has already been developed in XTMF's core but, there is no way to access it through the GUI.  This should be added.

**Comment by BrendanReilly** [comment]
Adding an option to override location where settings / configuration are pulled from is definitely the right thing to do.  An optional runtime argument can be provided to point XTMF's configuration to a non default location. Do you have any ideas for a more user-friendly way of overriding the default setting?

**Comment by JamesVaughan** [comment]
This is a good option, I was primarily thinking of augmenting the Settings page though to allow this functionality.

**Comment by Nasterska** [comment]
Does this require setting the non-default location each time XTMF is run? I see this as something that should be set once, and then retained each time that particular XTMF is run, unless and until changed again by the user.

**Comment by BrendanReilly** [comment]
In both cases it would be set once, but the one I mentioned seems less ideal because it involves adding the parameter manually through the properties dialog in Windows.  But
![Why not both?](https://cdn.meme.am/cache/instances/folder366/62440366.jpg)

**Comment by JamesVaughan** [comment]
I think having multiple options is a good idea.

**Comment by Nasterska** [comment]
👍👍

**Comment by BrendanReilly** [comment]
This has been added to the most recent commit on the development branch. You can override which configuration file gets loaded by including another / override Configuration.xml in the same directory as the XTMF executable that you are running. You can also specify the path / name of the Configuration file to use by passing --configuration "path/to/configuration/xml" as a command line argument.

**Comment by BrendanReilly** [comment]
There is an option on the settings page to create a local copy of the configuration file (which forces the gui to reload under the new configuration context). There is an option displayed to remove the local file if you want to return to the global / shared config.

**Comment by JamesVaughan** [comment]
This is now implemented.
