### ISSUE TITLE
Module Reordering

### ISSUE THREAD

**Issue by BrendanReilly** [TravelModellingGroup/XTMF#37]
Add drag and drop functionality for module reordering as an alternative to the keyboard shortcuts already present.

**Comment by JamesVaughan** [comment]
This was previously done before in XTMF 1.0.  We took this feature out for XTMF 1.1 because model systems were accidently edited too often.  This could be remedied by having better visual cues that an edit has occurred.

**Comment by BrendanReilly** [comment]
This feature is now available in XTMF 1.5.
