### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by kainagel** [TravelModellingGroup/XTMF#4]
Hi,

Very nice that the Toronto efforts are now available.

Was trying to compile it on mac.  Am no C# expert, so I may be getting everything completely wrong.  I installed Xamarin, and it seems to make halfway sense out of the code.  But I have consistent problems with expressions of type
                if((var oldType = RealModelSystemStructure.Type) != value)
; it is ok with
		var oldType = RealModelSystemStructure.Type ;
		if( oldType != value)
Presumably, my compiler is just not modern enough, but I don't think there is anything I can do about it.  Any chance to convince you to stay at compiler levels that are available across many platforms?

(It looks like there will be additional problems beyond the above one, but I thought I could still ask.)

Thank you and best regards

Kai Nagel, TU Berlin

**Comment by JamesVaughan** [comment]
Good catch, currently I'm working with a preview build of the Roslyn compiler and it does accept this syntax at the moment, however in the future this expression will no longer be supported so I'll make an effort to remove it today.

**Comment by JamesVaughan** [comment]
997f846f00cd1ad758364175ea51cf15e5261aca removed all usage of future C# syntax.  Now, the graphical interface for XTMF that we've currently implemented was done with WPF.  WPF is unfortunately not available on Linux/Mac.  The core of XTMF should still work though, and we do use Linux boxes to run "XTMF.RemoteClient" for our estimations.
