### ISSUE TITLE
Create a way of easily comparing model systems

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#44]
Currently model systems can be compared when they are copied out in text form. This will flag inconsequential differences, such as module index changes, making it difficult to sift through and determine what actual changes have been made to the model system. It would be especially useful for troubleshooting run results to have a way of easily obtaining a list of changes to both model system structure, as well as parameter values.

**Comment by JamesVaughan** [comment]
Working towards this, all types are ordered alphabetically before being assigned indexes.  This will help keep model systems to have less differences as long as a new type is not introduced.

**Comment by JamesVaughan** [comment]
This feature is being looked into for XTMF2.
