### ISSUE TITLE
Previous runs ordered by date (most recent first)

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#45]
Currently Previous Runs are ordered alphabetically. When searching for the most recent run, it would be easier to find it if these runs were ordered by the date and time they were run instead.

**Comment by mattaustin222** [comment]
100% agree. I rarely use 'Previous Runs', but when I do I am always annoyed by trying to find things. If you know the name enough to look for it alphabetically, the search bar is there.

**Comment by JamesVaughan** [comment]
Implemented in 11e606551b691819c8e603cc27de914dc6d78cc0.
