### ISSUE TITLE
Indicate when modules are disabled.

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#49]
I am a big fan of the disabling modules feature; however I sometimes forget whether my current ms has disabled modules or not, and have to dig through to check. It would be great to have some indicator, either in the root module, or some other visible area, that the model system contains disabled  modules, as a warning to the user. Probably would be best if the number of disabled modules was indicated as well.

**Comment by JamesVaughan** [comment]
Our current thoughts on this would be to include a third tab on the properties' pane for a "Model System Summary" where disabled modules would be included.  In addition a warning would be displayed when executing a model system containing disabled modules.
