### ISSUE TITLE
Root module display

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#53]
When I have a module that has a large collection of sub-modules (e.g: time period setup and assignment), and I am editing one of the sub-modules, I cannot see the root modules, so I have to scroll up and check which time period I am actually working in. This is clumsy and increases the potential for errors. Possible solution: retaining the root modules in the display as you scroll down? Or some other graphical solution?

**Comment by JamesVaughan** [comment]
I have also had this issue.  We need to put more thought into this.  A solution I'm contemplating is having a navigation pane that shows the currently selected module's ancestry.

**Comment by mattaustin222** [comment]
This is a great idea. On a similar note, I think there is a broader need for stronger module identification. For example, when I went to investigate Monika's comment, I also noticed that the name you provide a module doesn't show up on the parameter panel, only in the tree. This could cause similar confusion when every sub-module is labelled only as "FilePathFromInputDirectory".
