### ISSUE TITLE
multiple runs simultaneously 

### ISSUE THREAD

**Issue by bilalyusuf** [TravelModellingGroup/XTMF#62]
The ability to have multiple runs active at the same time, as long as they are targeting different emmebanks

**Comment by JamesVaughan** [comment]
We will figure out of this is feasible for the 1.4 release on Monday.  The workaround currently is to just have 2 copies of XTMF1.4 open at the same time, but since we've separated the run process from the GUI this is much closer to being possible.

**Comment by JamesVaughan** [comment]
This issue is going to be implemented together with #46 with a new subsystem in XTMF1.X to handle the execution of runs.
