### ISSUE TITLE
Rename window difficult to read

### ISSUE THREAD

**Issue by PeterKucirek** [TravelModellingGroup/XTMF#68]
I'm not sure if this is a result of my choice of theme, but I tried renaming a module and found black text on a dark-blue background. Naturally, this is difficult to read.

![image](https://user-images.githubusercontent.com/9703332/35983629-646bc572-0cc0-11e8-90e2-75c690717242.png)

I believe that I'm using the latest 1.4 development version (@JamesVaughan can confirm) 

Just wanted to you give y'all a quick heads-up.

**Comment by BrendanReilly** [comment]
There are still some places that are using the incorrect colours - thanks for noticing this!
