### ISSUE TITLE
Ability to search for /display modules that are missing in model system

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#70]
Would be nice to have a quick way to navigate to these without having to start a run and having it crash.

**Comment by BrendanReilly** [comment]
This is a good idea - it shouldn't require launching (and failing) a model system to get this information. In 1.3 there was the "Model System Information" tab which was added which used to collect the validation errors, but still required a failed run.
I'll add another function apart from run to do simple validation and enumerate the missing modules.
