### ISSUE TITLE
Backwards Comptibility - 1.4 vs 1.3

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#71]
Hello,

I am able to export model systems from 1.3 to 1.4 with no issues, but that is not the case when doing the reverse. 
When importing from 1.4 to 1.3, all of my TMG.Input.FilePathFromOutputDirectory modules disappear. They also cannot be copied over individually.

**Comment by JamesVaughan** [comment]
This is working as intended.
