### ISSUE TITLE
RunWindow console output should auto prepend module information and log message time

### ISSUE THREAD

**Issue by BrendanReilly** [TravelModellingGroup/XTMF#78]
Currently the RunWindow just displays (verbatim) log and console messages from modules without any higher-level formatting. Update the console output so it behaves more similarly to classical loggers by including a module name and time-stamp for each line of the log output.

It may also be beneficial for some users to allow customization of the date and line formatting output.

**Comment by PeterKucirek** [comment]
I would also recommend echoing the logs to a text file. It helps with a number of activities, including performance benchmarking, run debugging, and run analysis.

**Comment by JamesVaughan** [comment]
I have added this to #77.

**Comment by JamesVaughan** [comment]
Additionally this should also include something to limit the number of logs that the console is actually storing. Right now if you dump enough to the screen it will eventually run out of memory / max string length and crash.
