### ISSUE TITLE
Allow Queued runs to be reordered

### ISSUE THREAD

**Issue by JamesVaughan** [TravelModellingGroup/XTMF#79]
Currently a run will only in the order they were issued, but during that time a run might become a higher priority.  The order of these runs should be able to be changed before they start their execution.

**Comment by Nasterska** [comment]
Similarly, deleting a queued run from queue would be useful.

**Comment by JamesVaughan** [comment]
@Nasterska You must have read my mind.  This was just patched into 1.4 and will be part of Beta 3.
