### ISSUE TITLE
Ability to disable a module from running during a specific run

### ISSUE THREAD

**Issue by TrajceNikolov** [TravelModellingGroup/XTMF#8]
It would be very helpful to have the ability to disable (grey out) a specific module from running. This way, I do not have to delete and re-add modules every time I want to run a specific model system.

**Comment by JamesVaughan** [comment]
This feature has been implemented in the XTMF Core.  A GUI interface still needs to be developed.

**Comment by JamesVaughan** [comment]
Latest dev build seems to be working.  Additional testing is required.
