### ISSUE TITLE
Display advanced run options by default

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/XTMF#88]
It would be nice to see these without the drop-down... i have accidentally queued several runs...

![image](https://user-images.githubusercontent.com/13339423/38691258-5e7b9100-3e4e-11e8-858f-c7543fc63d9e.png)

**Comment by Nasterska** [comment]
Or alternatively, make it clear what the default/selected option is.

**Comment by BrendanReilly** [comment]
I've made an update so the advanced run options will be expandable by default.
