### ISSUE TITLE
Ability to create regions of modules

### ISSUE THREAD

**Issue by TrajceNikolov** [TravelModellingGroup/XTMF#9]
Give the ability to group modules in a list through XTMF for better visual representation.

**Comment by PeterKucirek** [comment]
Seconded. This is especially useful for big model systems.


Sent from Samsung Mobile

TrajceNikolov <notifications@github.com> wrote:

Give the ability to group modules in a list through XTMF for better visual representation

-

**Comment by JamesVaughan** [comment]
@BrendanReilly has started to look into this issue.  Currently we are exploring different options.  One of them is to provide different "Views" into the model system.  You would be able to switch between these views and the current view using a button in the menu as imaged below.
![image](https://user-images.githubusercontent.com/4054998/42707821-69e064aa-86a9-11e8-85f0-3e91a830266c.png)

We are looking for feedback at this time before continuing forward.
