### ISSUE TITLE
provide logs from each client on the main window during estimation run

### ISSUE THREAD

**Issue by bilalyusuf** [TravelModellingGroup/XTMF#93]
When doing an estimation run, currently the only message that gets piped back to the main model system window is if a client crashes. It would be beneficial to know exactly what each client is logging if it can be done in the clean way, maybe under each clients progress bar rather than the main logging window.

**Comment by JamesVaughan** [comment]
If the XTMF.RemoteClient.exe replaced the Console.Out stream and started piping that back through XTMF.Networking this could be done pretty easily.

**Comment by JamesVaughan** [comment]
Currently the console writes are written back to the main logging window.  For 1.6 we will look into having different consoles for each client.

**Comment by BrendanReilly** [comment]
For clarification - you mean in the run display? So for example, if there were 5 remote clients, there would be 5 separate consoles displayable?
